### ISSUE TITLE
:raising_hand: node subset of components

### ISSUE THREAD

**Issue by fmigneault** [DACCS-Climate/DACCS-executive-committee#1]
### Topic category

Select which category your topic relates to:

- [x] software architecture
- [ ] potential risks
- [x] federation decisions
- [x] opportunities for growth
- [ ] other

### Topic summary

How to handle partial subsets of default services, and which minimal set we would consider to be a "valid" DACCS node.

### Supporting documentation

Details in https://github.com/bird-house/birdhouse-deploy/issues/357

### Additional information

n/a

**Comment by mishaschwartz** [comment]
Resolved in https://github.com/bird-house/birdhouse-deploy/pull/399
