### ISSUE TITLE
:raising_hand: OGC Open Science Persistent Demonstrator Request for Information

### ISSUE THREAD

**Issue by huard** [DACCS-Climate/DACCS-executive-committee#10]
### Topic category

Select which category your topic relates to:

- [ ] software architecture
- [ ] potential risks
- [ ] federation decisions
- [x] opportunities for growth
- [ ] other

### Topic summary

OGC published an Open Science Persistent Demonstrator Request for Information
https://www.ogc.org/initiatives/open-science/

> The goal is to enable and demonstrate prototyping technology solutions that create capacity for better and faster Earth Science research, comparison scenarios, as well as higher adoption of EO-based results and impact on society.  Ultimately, the Open Science Persistent Demonstrator will be a 24/7 available web application that demonstrates and tests scientific workflows across several existing platforms. The goal is to demonstrate how platforms operated by different organizations can be used for collaborative research and data representation.

I believe it is in our interest to submit Marble. 

Answers due 17 September 2023.

### Supporting documentation

Documentation: https://www.ogc.org/wp-content/uploads/2023/07/18.7.23.RFI_OSPD.pdf

Survey: https://www.surveymonkey.com/r/OSPDSurvey

### Additional information

Provide any additional information below

**Comment by fmigneault** [comment]
Other information page: https://www.ogc.org/initiatives/open-science/
