### ISSUE TITLE
:raising_hand: DACCS network name

### ISSUE THREAD

**Issue by mishaschwartz** [DACCS-Climate/DACCS-executive-committee#2]
### Topic category

Select which category your topic relates to:

- [ ] software architecture
- [ ] potential risks
- [ ] federation decisions
- [ ] opportunities for growth
- [x] other: branding

### Topic summary

Briefly describe the topic you wish to discuss below

What should we name the federated network of nodes?

### Supporting documentation

Provide links to any supporting documentation that is relevant to your topic.

Some initial thoughts from @dchandan: https://docs.google.com/presentation/d/1ZXY-C-AWxbUQp0Un0_k0WWwl9uJ1LLY_6nDCgVFp9BI/edit#slide=id.p

### Additional information

Provide any additional information below

Previously discussed:

- DACCS is no good because it shares an acronym with Direct Air Carbon Capture and Sequestration
- We want something that is climate-related
- We don't want something that brings to mind a specific region or type of climate analysis/research
- We don't want something that is tied to another project
- An acronym is nice but not necessary

**Comment by fmigneault** [comment]
Multiple participants of the committee (including myself) mentioned the problematic name of "Glacier" being too closely related to ice, and therefore, probably not adequate for other climate studies such as wildfires and other extreme climate events.

The "Marble" name seems like a potential candidate. 
However, it maybe still lacks some meaning (no acronym/backronym yet) to justify it being the best option.
@dchandan brought the point that it fits with the current DACCS logo, so it could be reused directly.

More voting and querying of other participants feedback is needed to come to a decision.

**Comment by fmigneault** [comment]
See also insight from @tlvu https://github.com/DACCS-Climate/DACCS-executive-committee/pull/3#discussion_r1270997112 regarding "Glacier".

**Comment by Maximo-P** [comment]
Hello,

I've found that Marble is the name for an open-source globe and world map software. Reference here: https://marble.kde.org/

When is the deadline to submit the abstract to AGU ? Would this cause a conflict if we present the DACCS network name as Marble ?

**Comment by dchandan** [comment]
I feel like there is very little overlap between our Marble and this KDE application for any confusion between the two.

But, if you search "Marble climate" then there is a potentially bigger problem. There seems to be venture capital firm that backs climate related companies called [Marble](https://marble.studio). This can be problematic.... 

The deadline for the AGU abstracts is Aug 2. So if this new information about the similarly named venture firm poses a problem for us going with this name, then I think we'll just have to go with a phrase like "the DACCS team is building a platform for ...." for the abstract. 

Thoughts?

**Comment by mishaschwartz** [comment]
@dchandan 
> I think we'll just have to go with a phrase like "the DACCS team is building a platform for ...." for the abstract.

I think that this phrasing is fine

**Comment by fmigneault** [comment]
Although a closed issue, listing a few conflicts that I came across recently regarding "Marble" name:

- https://www.osgeo.org/projects/marble/
- https://climatebase.org/company/1132896/marble?source=orgs_directory&queryID=5ad2bd22c65115216c97351a611c8890 (or https://marble.studio/ directly)
- https://www.marbleclimate.org/  (especially that one, similar URI easily confused with this network: https://marbleclimate.com/)

Maybe something to consider when mentioning the "Marble" name. People might be really confused about what we are actually referring to provided that some (OSGeo notably) as a much wider community.
